# @file
# Tripal Blast Configuration Entity Schema

tripal_blast.tripalblastdatabase.*:
  type: config_entity
  label: 'BLAST Configuration Entity'
  mapping:
    id:
      type: 'integer'
      label: 'Database Entity ID'
    name:
      type: 'string'
      label: 'Name'
    path:
      type: 'string'
      label: 'Path'
    dbtype:
      type: 'string'
      label: 'Database Type'
    dbxref_id_regexp:
      type: 'string'
      label: 'DB Xref Id Regexp'
    dbxref_db_id:
      type: 'integer'
      label: 'DB Xref Id'
    dbxref_linkout_type:
      type: 'string'
      label: 'DB Xref Type'
    cvitjs_enabled:
      type: 'boolean'
      label: 'CvitJS Enabled'
    